#include <stdio.h>
#include "main.h"
/**
 * main - Fibonacci sequence is generated by adding the previous two terms
 *
 * Return: 0 (success)
 */
int main(void)
{
	int before, current, after, sum, ref;

	before = 1;
	current = 2;
	after = before + current;
	ref = 4000000;
	sum = 2;

	for (; after <= ref;)
	{
		after = before + current;
		if ((after % 2) == 0)
		{
			sum = sum + after;
		}
		before = current;
		current = after;
	}
	printf("%d", sum);
	printf("\n");
	return (0);
}
